// Letter Sort presets. Stored in-app for the Lesson Planner picker.
// (Runtime wiring into the Letter Sort lesson step is pending — these presets
//  drive the standalone Letter Sort page via Supabase today.)
export default {
  "M1.L16.F.A1": { "syllables": ["mo","mi","ma","mu","me"], "words": [], "syllcmp": "equals", "syllmatch": "initial", "per": 4 },
  "M4.L16.CF.A1": { "syllcount": [2,3,4], "words": ["queso","gato","cama","gelatina","pelota","boli..grafo","xilo..fono","lupa"] },
  "M6.L1.CF.A1": { "syllcount": [2,3,4], "words": ["hamburguesa","gallina","gato","nido","gota","ventana","autobuses","galletas","escalera"] },
  "M6.L2.CF.A1": { "syllcount": [2,3,4], "words": ["velero","gallina","chocolate","juguetes","grillo","caballo"] },
  "M6.L2.F.A1": { "syllables": ["ga","go","gu"], "words": ["gato","gota","fogata","canguro","soga","aguja","gusano","gorro"], "syllcmp": "prefix", "syllmatch": "any", "per": 4 },
  "M6.L2.F.A2": { "syllables": ["ga","go","gue","gui"], "words": ["golosina","a..guila","hormiguita","gallina","regadera","juguetes","espaguetis","guitarra"], "syllcmp": "prefix", "syllmatch": "any", "per": 4 },
  "M6.L14.CF.A1": { "phonemes": [3,4,5], "words": ["bote","jamón","cerdo","mar","sol","cama"], "per": 4 },
  "M6.L16.CF.A1": { "syllables": ["ce","ci"], "words": ["cebra","cigüeña","cocina","pecera","bici","cepillo"], "syllcmp": "prefix", "syllmatch": "any", "per": 4 },
  "M6.L18.F.A1": { "mode": "rowsyll", "rows": "cebra:init;bici:final", "words": ["ceja","dulce","dice","cima","once","cero","hace","cine"], "rowtitle": false, "hidewords": false },
  "M7.L1.F.A1": { "syllables": ["ña","ñe","ñi","ño","ñu"], "words": ["muñeca","pañuelo","niño","meñique","uña"], "splitcards": true, "syllmatch": "any", "syllcmp": "prefix" },
  "M7.L3.F.A1": { "mode": "rowsyll", "rows": "muñeca:second;niña:final", "words": ["señala","cariño","teñí","mañana","meñique","daño"], "rowtitle": false, "hidewords": false },
  "M7.L6.F.A1": { "syllables": ["ge","gi"], "words": ["giro","rugido","genio","ruge"], "tilesonly": "true", "syllcmp": "prefix", "syllmatch": "any", "per": 4 },
  "M7.L8.CF.A1": { "mode": "generate", "columns": ["tazón","sano"], "rows": [4,4], "slots": 2 },
  "M7.L8.F.A1": { "mode": "rowsyll", "rows": "página:second;esfinge:final", "words": ["rugido","recoge","ingenio","elegí"], "rowtitle": false, "hidewords": false },
  "M7.L12.F.A1": { "syllables": ["che","chi","cho","güe","güi"], "words": ["salchichas","cebolla","cigüeña","pingüinos","pollito","chocolate","noche"], "syllmatch": "any", "syllcmp": "prefix" },
  "M7.L16.F.A1": { "syllables": ["yo","za","ji","cho","go"], "words": ["yogur","cebra","guitarra","zapato","chocolate","jirafa","gota"], "syllmatch": "any", "syllcmp": "prefix" },
  "M7.L18.F.A1.1": { "mode": "rowsyllcols", "rowsyll": "ya,ye,yi,yo,yu|za,ze,zi,zo,zu", "headerimages": ["yayeyiyoyu.png","zazezizozu.png"], "words": ["zanahorias","yema","zapato","yogur","zorro"] },
  "M7.L18.F.A1.2": { "mode": "rowsyllcols", "rowsyll": "ha,he,hi,ho,hu|ja,je,ji,jo,ju", "headerimages": ["hahehihohu.png","jajejijoju.png"], "words": ["hamaca","jirafa","helado","joyas","hoja"] },
  "M7.L18.F.A1.3": { "mode": "rowsyllcols", "rowsyll": "ña,ñe,ñi,ño,ñu|cha,che,chi,cho,chu", "headerimages": ["n..an..en..in..on..u.png","chachechichochu.png"], "words": ["niño","chaleco","mañana","chivo","mapache"] },
  "M7.L18.F.A1.4": { "mode": "rowsyllcols", "rowsyll": "ga,go,gu|gue,gui", "headerimages": ["gagogu.png","guegui.png"], "words": ["gota","guepardo","águila","aguja","manguera"] },
  "M7.L18.F.A1.5": { "mode": "rowsyllcols", "rowsyll": "güe,güi|ge,gi", "headerimages": ["gu,,egu,,i.png","gegi.png"], "words": ["gemelo","pingüinos","girar","agitar","bilingüe"] },
  "M7.L18.F.A1.6": { "mode": "rowsyllcols", "rowsyll": "ce,ci", "headerimages": ["ceci.png"], "words": ["cero","cocina","osito","doce","cepillo","caza","bocina"] },
  "M8.L2.F.A1": { "mode": "syllgroups", "groups": ["k","x","w"], "headerimages": ["k.png","x.png","w.png"], "words": ["karate","wi-fi","kínder","ukelele","saxo","boxeo"], "wordimages": 0 },
  "M8.L6.F.A1": { "mode": "generate", "columns": ["A","B","C","D"], "rows": [6], "slots": 1 },
  "M8.L6.F.A2": { "mode": "generate", "columns": ["E","F","G"], "rows": [8], "slots": 1 },
  "M8.L7.F.A1": { "mode": "generate", "columns": ["H","I","J","K"], "rows": [8], "slots": 1 },
  "M8.L7.F.A2": { "mode": "generate", "columns": ["L","M","N"], "rows": [8], "slots": 1 },
  "M8.L8.F.A1": { "mode": "generate", "columns": ["Ñ","O","P","Q"], "rows": [8], "slots": 1 },
  "M8.L8.F.A2": { "mode": "generate", "columns": ["R","S","T"], "rows": [8], "slots": 1 },
  "M8.L9.F.A1": { "mode": "generate", "columns": ["U","V","W","X","Y","Z"], "rows": [6], "slots": 1 },
  "M8.L11.F.A1": { "mode": "generate", "columns": ["tra","tru","tri","bra","bro"], "rows": [6], "slots": 1 },
  "M8.L13.F.A1": { "mode": "syllgroups", "groups": ["br","tr"], "titles": ["brócoli","trompo"], "words": ["letra","brazo","postre","libre","cabra","atrapa"] },
  "M8.L16.F.A1": { "mode": "generate", "columns": ["gra","gru","pre","pri","pro"], "rows": [6], "slots": 1 },
  "M9.L1.F.A1": { "mode": "generate", "riddle": "En el verano, como muchas |fr||utas.|", "columns": ["",""], "rows": [4], "slots": 1 },
  "M9.L1.F.A2": { "mode": "generate", "riddle": "Como frutas con |cr||ema.|", "columns": ["",""], "rows": [4], "slots": 1 },
  "M9.L1.F.A3": { "mode": "generate", "riddle": "Me gusta el pollo |fr||ío.|", "columns": ["",""], "rows": [4], "slots": 1 },
  "M9.L1.F.A4": { "mode": "generate", "riddle": "Cristina cree que la copa es de |cr||istal.|", "columns": ["",""], "rows": [4], "slots": 1 },
  "M9.L1.F.A5": { "mode": "generate", "riddle": "Tengo un frasco lleno de |fr||ijoles.|", "columns": ["",""], "rows": [4], "slots": 1 },
  "M7.L16.Reading.A1": { "mode": "sort", "words": ["interesado","emocionado","entusiasmado","fascinado"], "layout": "horizontal", "direction": "left-right", "left": "menos interesado", "right": "más interesado" },
  "M8.L18.F.A1": { "mode": "syllgroups", "groups": ["gr","pr"], "titles": ["tigre","pregunta"], "words": ["gris","siempre","premio","logro","gracias","compré"] },
  "M9.L3.F.A1": { "mode": "rowsyllcols", "groups": "fr|cr|dr", "layout": "top", "headertype": "image", "cardtype": "word", "match": "contains", "words": ["crema","fresa","madre","cuadro","frío","escribo"], "hidetitle": true },
  "M9.L6.F.A1": { "mode": "rowsyllcols", "groups": "blan|cla|bles", "layout": "top", "headertype": "text", "cardtype": "image", "match": "contains", "words": ["teclado","rana","blanco","muebles","bellota","clarinete","clavo"], "hidetitle": true },
  "M9.L8.F.A1": { "mode": "rowsyllcols", "groups": "cl|bl", "layout": "top", "headertype": "image", "cardtype": "word", "match": "contains", "words": ["pueblo","teclado","clase","doble","clavo","blusa"], "hidetitle": true },
  "M9.L10.CLC": { "mode": "manualsort", "headers": "barn,ocean", "answers": "barn:sheep,chicken|ocean:octopus,seahorse,whale", "layout": "top", "headertype": "image", "cardtype": "image", "hidetitle": true },
  "M9.L11.F.A1": { "mode": "generate", "columns": ["fle","flo","gla","pla","plu"], "rows": [8], "slots": 1 },
  "M9.L13.F.A1": { "mode": "rowsyllcols", "groups": "pl|fl|gl", "layout": "top", "headertype": "image", "cardtype": "word", "match": "contains", "words": ["flecha","regla","playa","inglés","infla","simple","pluma","flores","globo"], "hidetitle": true }
};