// Word Builder presets. Stored in-app for the Lesson Planner picker AND used
// at runtime by the Word Builder lesson step (no Supabase fetch needed).
// NOTE: duplicate keys in the source file keep the last definition (JS behavior).
export default {
  "M5.L19.F.A1": { "label": "M5 · L19 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 6, "letters": [], "syllables": [], "words": ["a","ba","be","bo","bu","bi","e","ca","co","cu","que","qui","i","lla","lle","lli","llo","llu","o","ra","re","ri","ro","ru","u","rra","rre","rri","rro","rru","va","ve","vi","vo","vu"], "toggles": { "space": false, "caps": true, "accent": true, "punc": false } } },
  "M6.L4.F.A1": { "label": "M6 · L4 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 3, "letters": [], "syllables": ["ga","go","gue","la","Mi","na","pa"], "words": [], "toggles": { "space": false, "caps": true, "accent": false, "punc": false } } },
  "M6.L9.F.A1": { "label": "M6 · L9 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 7, "perRow": 2, "letters": [], "syllables": ["la","ma","po","ra","tu","yo","zo"], "words": [], "answers": ["pozo","lazo","mazo","mayo","tuyo","rayo","mala"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M6.L14.F.A1": { "label": "M6 · L14 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 3, "letters": [], "syllables": ["da","go","ha","hi","Hu","jo","ju"], "words": [], "answers": ["hada","hago","jugo","Hugo","higo","hijo"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M6.L19.F.A1": { "label": "M6 · L19 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 2, "letters": [], "syllables": ["ce","cie","Ci","ro","rro","lo"], "words": [], "answers": ["cierro","cielo","lo","loro","cero","Ciro"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M6.L20.F.A1": { "label": "M6 · L20 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 2, "letters": [], "syllables": [], "words": ["ella","pregunta","siempre","barco","estrellas","sobre","hace","mejor","ya","cumpleaños","ha","muy","galletas","el","mi","es","pastel","mesa","la","sobre"], "answers": ["¿Ella siempre hace galletas?","Es mi cumpleaños.","El pastel está sobre la mesa."], "toggles": { "space": true, "caps": true, "accent": false, "punc": true, "images": false, "write": true } } },
  "M7.L4.F.A1": { "label": "M7 · L4 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 2, "letters": [], "syllables": ["a","ba","ca","ni","ña","ño"], "words": [], "answers": ["año","caño","caña","cabaña","baña","niña"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M7.L9.F.A1": { "label": "M7 · L9 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 2, "letters": [], "syllables": ["ge","gen","gi","ma","mi","te"], "words": [], "answers": ["gema","gima","gime","me","mete","gente"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M7.L14.F.A1": { "label": "M7 · L14 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 3, "letters": [], "syllables": ["a","co","güe","no","pa","che","per","ra","ro"], "words": [], "answers": ["anoche","noche","coche","cochero","perchero","paragüero"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M7.L18.F.A2.1": { "label": "M7 · L18 · Word Builder · F · A2.1", "content": { "boxes": 1, "rows": 1, "perRow": 2, "letters": [], "syllables": ["pi","ña","|","^","ta"], "words": [], "toggles": { "space": false, "caps": true, "accent": true, "punc": false, "images": false } } },
  "M7.L18.F.A2.2": { "label": "M7 · L18 · Word Builder · F · A2.2", "content": { "boxes": 1, "rows": 1, "perRow": 3, "letters": [], "syllables": ["mon","ta","ña"], "words": [], "toggles": { "space": false, "caps": true, "accent": true, "punc": false, "images": false } } },
  "M7.L18.F.A2.3": { "label": "M7 · L18 · Word Builder · F · A2.3", "content": { "boxes": 1, "rows": 1, "perRow": 2, "letters": [], "syllables": ["ta","za","|","^","ti"], "words": [], "toggles": { "space": false, "caps": true, "accent": true, "punc": false, "images": false } } },
  "M7.L19.F.A1": { "label": "M7 · L19 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 5, "perRow": 11, "letters": [], "syllables": ["a","ya","za","ha","ja","ña","cha","ga","|","e","ye","ze","he","je","ñe","che","gue","güe","ge","ce","|","i","yi","zi","hi","ji","ñi","chi","gui","güi","gi","ci","|","o","yo","zo","ho","jo","ño","cho","go","|","u","yu","zu","hu","ju","ñu","chu","gu"], "words": [], "toggles": { "space": false, "caps": true, "accent": true, "punc": false, "images": false } } },
  "M7.L20.F.A1": { "label": "M7 · L20 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 4, "perRow": 3, "letters": [], "syllables": [], "words": ["libro","nuevo","primero","aprender","dentro","pequeño","animales","gracias","madre","cómo","cuando","encuentra"], "answers": ["Mi madre no encuentra el tesoro.","Gracias por el libro."], "toggles": { "space": true, "caps": true, "accent": true, "punc": true, "images": false, "write": true } } },
  "M8.L4.F.A1": { "label": "M8 · L4 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 5, "perRow": 4, "letters": [], "syllables": ["e","fón","ge","ki","ko","lo","wi","xi"], "words": [], "answers": ["kiwi","kilo","lo","xilofón","exige"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M8.L14.F.A1": { "label": "M8 · L14 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 3, "letters": [], "syllables": ["a","bra","e","fi","to","tra","tro"], "words": [], "answers": ["fibra","abra","a","atrae","trato","troto"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M8.L19.F.A1": { "label": "M8 · L19 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 2, "letters": [], "syllables": ["do","gra","gru","mo","pra","pri"], "words": [], "answers": ["grumo","primo","gramo","grado","do","prado"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M8.L20.F.A1": { "label": "M8 · L20 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 4, "perRow": 3, "letters": [], "syllables": [], "words": ["más","música","quienes","|","letra","nombre","todo","|","crecer","material","tierra","|","cosa","grupo","tarea"], "answers": ["Mi madre no encuentra el tesoro.","Gracias por el libro."], "toggles": { "space": true, "caps": true, "accent": true, "punc": true, "images": false, "write": true } } },
  "M9.L4.F.A1": { "label": "M9 · L4 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 3, "letters": [], "syllables": ["ce","cre","cru","dre","fre","ma","o"], "words": [], "answers": ["crece","cruce","ofrece","ocre","crema","madre"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M9.L9.F.A1": { "label": "M9 · L9 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 6, "perRow": 3, "letters": [], "syllables": ["a","ble","ca","cla","ma","ro","ve","vo"], "words": [], "answers": ["clavo","clave","claro","aclaro","amable","cable"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "M9.L14.F.A1": { "label": "M9 · L14 · Word Builder · F · A1", "content": { "boxes": 1, "rows": 5, "perRow": 3, "letters": [], "syllables": ["ca","do","fla","glés","in","ya","pla"], "words": [], "answers": ["playa","placa","flaca","inflado","inglés"], "toggles": { "space": false, "caps": true, "accent": false, "punc": false, "images": false } } },
  "Group1": { "label": "Creando sílabas", "content": { "boxes": 1, "rows": 6, "perRow": 5, "letters": ["a","e","i","o","u","m","p","s","l"], "syllables": [], "words": [], "toggles": { "space": false, "caps": true, "accent": false, "punc": false } } },
  "Group2": { "label": "Creando palabras", "content": { "boxes": 1, "rows": 6, "perRow": 5, "letters": ["a","e","i","o","u","m","p","s","l"], "syllables": ["test"], "words": [], "toggles": { "space": false, "caps": true, "accent": false, "punc": false } } },
  "Group3": { "label": "Creando palabras (ampliado)", "content": { "boxes": 1, "rows": 6, "perRow": 5, "letters": ["a","e","i","o","u","m","p","s","l","n","d","t","f"], "syllables": [], "words": [], "toggles": { "space": false, "caps": true, "accent": false, "punc": false } } }
};